### ISSUE TITLE
Feature: function to return type based on CC number

### ISSUE THREAD

**Issue by danielb2** [cjihrig/credit-card#13]
A function to return the type of CC based on the CC number would be useful

**Comment by bendrucker** [comment]
This is available in creditcards if you need it urgently:

https://github.com/bendrucker/creditcards#cardtypenumber--eager---string

**Comment by danielb2** [comment]
Thanks for the tip

**Comment by cjihrig** [comment]
@danielb2 I'll look into creating this today.

**Comment by bendrucker** [comment]
If you're interested, I have the type definitions separate from the general validators for creditcards:

https://github.com/bendrucker/creditcards-types

I've tried to keep the regexes strict enough to prevent any overlap so that the types can be safely checked in a loop that breaks as soon as a match is found.

**Comment by danielb2** [comment]
:+1:
